services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_demo_db
      MYSQL_USER: Fatz
      MYSQL_PASSWORD: Fatz123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - test_demo_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: Fatz
      PMA_PASSWORD: Fatz123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - test_demo_network
      
volumes:
  mysql_data:

networks:
  test_demo_network: